sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json

script:
  - docker run -e CI=true hluandeloitte/react-test npm test

after_success:
  - docker build -t hluandeloitte/multi-client ./client
  - docker build -t hluandeloitte/multi-nginx ./nginx
  - docker build -t hluandeloitte/multi-server ./server
  - docker build -t hluandeloitte/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  # take those images and push them to docker hub
  - docker push hluandeloitte/multi-client
  - docker push hluandeloitte/multi-nginx
  - docker push hluandeloitte/multi-server
  - docker push hluandeloitte/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-627232598463
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
